name: Micronotes Notes Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: false

      - name: Build Docker image
        run: |
          docker build --no-cache . -t ${{ secrets.DOCKERHUB_USERNAME }}/micronotes-notes-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/micronotes-notes-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/micronotes-notes-service:latest
        continue-on-error: false

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/micronotes-notes-service:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/micronotes-notes-service:latest
